# Generated by Django 5.0.6 on 2024-10-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0004_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
