# Generated by Django 5.0.6 on 2024-10-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0006_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishers',
            field=models.CharField(max_length=100),
        ),
    ]
