# Generated by Django 5.0.6 on 2024-10-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0008_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_summary',
            field=models.TextField(default='No summary available'),
        ),
    ]
