# Generated by Django 5.0.6 on 2024-10-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0010_rename_book_summary_book_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(),
        ),
    ]
