# Generated by Django 5.1.2 on 2024-12-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0014_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(),
        ),
    ]
